CXX = g++
USE_OMP = y
DEBUG = n
UNIT_TESTING = n
CXXFLAGS = -std=c++11 -O3 -I./ -I/home/ccheng32/project/lib/include 
LIBS = -L./ -L/home/ccheng32/project/lib/lib -l:libtrng4.a

ifeq ($(DEBUG),y)
	CXXFLAGS += -DDEBUG
endif

ifeq ($(UNIT_TESTING),y)
	CXXFLAGS += -DUNIT_TESTING
endif

ifeq ($(USE_OMP),y)
	CXXFLAGS += -fopenmp
	LIBS += -lgomp
endif
