CXX = g++
USE_OMP = y
DEBUG = y
UNIT_TESTING = n
CXXFLAGS = -std=c++11 -O3 -I./ -I/home/grhart2/Potts_ompGPU/_lit/trng/include -I${BOOSTROOT}/include
LIBS = -L./ -L/home/grhart2/Potts_ompGPU/_lit/trng/lib -ltrng4

ifeq ($(DEBUG),y)
	CXXFLAGS += -DDEBUG
endif

ifeq ($(UNIT_TESTING),y)
	CXXFLAGS += -DUNIT_TESTING
endif

ifeq ($(USE_OMP),y)
	CXXFLAGS += -fopenmp
	LIBS += -lgomp
endif
